package com.blakdragon.petscapeoffline.models.enums

enum class IronmanItem {
    Avernic,
    BandosGodsword,
    DragonWarhammer,
    BarrowsGloves,
    BarrowsItems10,
    BasiliskJaw,
    BladeOfSaeldor,
    AbyssalBludgeon,
    BottomlessBucketOfCompost,
    CerbBoots3,
    ChambersUnique,
    ChambersMegaRare1,
    CrystalToolSeed,
    DksRing1,
    DksRing3,
    DragonPick, //85 mining for hardcores
    DragonScimitar,
    DragonDefender,
    DragonHunterLance,
    EliteVoid,
    FerociousGloves,
    FighterTorso,
    FireCape,
    Fury,
    GloryAmulet,
    MountedGloryAmulet,
    GwdDrops6,
    ImbuedHeart,
    EternalGem,
    InfernalCape,
    KrakenTentacle,
    ImbuedMageCape, //Mage cape for hardcores
    MagesBook,
    MaxPool,
    HelmOfNeitiznot,
    OccultAmulet,
    OccultAltar,
    QuestCape,
    RigourAugury,
    RuneGloves,
    TheatreWeapon1,
    SlayerHelm,
    SpiritShield,
    TridentOfTheSeas,
    Void,
    AvasAccumulator,
    AbyssalQhipe,
    Zenyte2,
    Zenyte4,
    ZulrahUniques3
}
