package com.blakdragon.petscapeclan.models

import com.blakdragon.petscapeclan.models.enums.Rank
import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document
import java.time.LocalDate

@Document
class ClanMember(
    @Id var id: String? = null,
    val runescapeName: String,
    val rank: Rank,
    val joinDate: LocalDate,

    val abyssalOrphan: Boolean = false,
    val babyMole: Boolean = false,
    val callistoCub: Boolean = false,
    val hellpuppy: Boolean = false,
    val ikkleHydra: Boolean = false,
    val jalNibRek: Boolean = false,
    val kalphitePrincess: Boolean = false,
    val lilZik: Boolean = false,
    val littleNightmare: Boolean = false,
    val noon: Boolean = false,
    val olmlet: Boolean = false,
    val petChaosElemental: Boolean = false,
    val petDagannothPrime: Boolean = false,
    val petDagannothRex: Boolean = false,
    val petDagannothSupreme: Boolean = false,
    val petDarkCore: Boolean = false,
    val petGeneralGraardor: Boolean = false,
    val petKrilTsutsaroth: Boolean = false,
    val petKraken: Boolean = false,
    val petKreeArra: Boolean = false,
    val petSmokeDevil: Boolean = false,
    val petSnakeling: Boolean = false,
    val petZilyana: Boolean = false,
    val princeBlackDragon: Boolean = false,
    val scorpiasOffspring: Boolean = false,
    val skotos: Boolean = false,
    val sraracha: Boolean = false,
    val tzrekJad: Boolean = false,
    val venenatisSpiderling: Boolean = false,
    val vetionJr: Boolean = false,
    val vorki: Boolean = false,

    val babyChinchompa: Boolean = false,
    val beaver: Boolean = false,
    val giantSquirrel: Boolean = false,
    val heron: Boolean = false,
    val riftGuardian: Boolean = false,
    val rockGolem: Boolean = false,
    val rocky: Boolean = false,
    val tangleroot: Boolean = false,

    val bloodhound: Boolean = false,
    val chompyChick: Boolean = false,
    val herbi: Boolean = false,
    val lilCreator: Boolean = false,
    val petPenanceQueen: Boolean = false,
    val phoenix: Boolean = false,
    val tinyTempor: Boolean = false,
    val youngllef: Boolean = false,
    val smolcano: Boolean = false,

    val total1500: Boolean = false,
    val total2000: Boolean = false,
    val maxCape: Boolean = false,
    val base70Stats: Boolean = false,
    val base80Stats: Boolean = false,
    val base90Stats: Boolean = false,
    val combat126: Boolean = false,
    val questCape: Boolean = false,
    val achievementCape: Boolean = false,
    val musicCape: Boolean = false,
    val championCape: Boolean = false,
    val infernalCape: Boolean = false,
    val xericsGuard: Boolean = false,
    val xericsWarrior: Boolean = false,
    val xericsSentinal: Boolean = false,
    val xericsGeneral: Boolean = false,
    val xericsChampion: Boolean = false,
    val sinhazaShroud1: Boolean = false,
    val sinhazaShroud2: Boolean = false,
    val sinhazaShroud3: Boolean = false,
    val sinhazaShroud4: Boolean = false,
    val sinhazaShroud5: Boolean = false,
    val ironman: Boolean = false,
    val ultimateIronman: Boolean = false,
)
